server.port=80
userApi=https://fwcbj.linkingcloud.cn/Card/GetDefaultCard
docterApi=https://fwcbj.linkingcloud.cn/GuaHao/OrderDeptResources
ua=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) MicroMessenger/6.8.0(0x16080000) MacWechat/3.3(0x13030013) NetType/WIFI WindowsWechat

